name: Python CI

on: 
  push: 
    branches: [main]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-pyhton@v5
        with: 
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Lint code
        run: 
          pip install black
          black --check .